### ISSUE TITLE
Product list file specification

### ISSUE THREAD

**Issue by fraunos** [olivierhagolle/maja_peps#3]
Hi,
I could not find any information on how to create a file needed to start processing - namely `maja_products.txt` or called `prod_list_toulouse.txt` in README.
Thanks

**Comment by fraunos** [comment]
This would help enormously, as setting up MAJA on own machine is horrendously tricky.

**Comment by olivierhagolle** [comment]
Hi Fraunos, 
Sorry, I did not see the messages. Sorry too for the difficulties with MAJA set-up.

Did you manage ? The list is created in the first step (maja_peps_process.py) and is used to remember what you ordered in the second step (maja_peps_download.py)

The Maja processing at Peps was not fully robust so far, because of communication errors with CNES HPC center, but it is improving.

Best regards,
Olivier

**Comment by fraunos** [comment]
Hi Olivier,
That's fine, I was only helping another person with setting it up. I didn't have any progress and gave up.
It's an interesting project and wish you the best at improving it.

**Comment by olivierhagolle** [comment]
Thanks and sorry for the difficulties.
